version: '3.8'

services:
  chatbot:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    command: uvicorn server:app --host 0.0.0.0 --port 8000